[tool.towncrier]
package = "range_set"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/smurfix/range_set/issues/{issue}>`__"
